-- ============================================
-- 数据库: sx_civil_servant
-- 自动生成测试数据
-- ============================================
USE `sx_civil_servant`;

-- ----------------------------
-- Test data for: 公务员人员信息 (civil_servant_person)
-- ----------------------------
INSERT INTO `civil_servant_person` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `adult_status`, `cadre_mgmt_category`, `work_start_time`, `party_join_time_text`, `political_status`, `party_join_time`, `second_party`, `third_party`, `registration_time`, `person_mgmt_status`, `mgmt_category`, `id_card_no`, `stats_unit`, `resume`) VALUES ('吴艳', '男', '1998-05-03', '陕西省延安市', '陕西省延安市', '测试成年现状_1', '事业单位人员', '2025-07-12 08:20:50', '测试入党时间文字_1', '群众', '2023-10-18 08:06:29', '测试第二党派_1', '测试第三党派_1', '2021-12-12 14:01:53', '测试人员管理状态_1', '测试管理类别_1', '6101419483336328', '测试统计关系所在单位_1', '测试简历数据1');
INSERT INTO `civil_servant_person` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `adult_status`, `cadre_mgmt_category`, `work_start_time`, `party_join_time_text`, `political_status`, `party_join_time`, `second_party`, `third_party`, `registration_time`, `person_mgmt_status`, `mgmt_category`, `id_card_no`, `stats_unit`, `resume`) VALUES ('赵刚', '女', '1991-07-24', '陕西省延安市', '陕西省宝鸡市', '测试成年现状_2', '事业单位人员', '2022-08-13 12:32:24', '测试入党时间文字_2', '群众', '2022-08-15 16:04:09', '测试第二党派_2', '测试第三党派_2', '2025-12-10 08:34:53', '测试人员管理状态_2', '测试管理类别_2', '6101220780586820', '测试统计关系所在单位_2', '测试简历数据2');
INSERT INTO `civil_servant_person` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `adult_status`, `cadre_mgmt_category`, `work_start_time`, `party_join_time_text`, `political_status`, `party_join_time`, `second_party`, `third_party`, `registration_time`, `person_mgmt_status`, `mgmt_category`, `id_card_no`, `stats_unit`, `resume`) VALUES ('陈静', '女', '1985-08-25', '陕西省咸阳市', '陕西省渭南市', '测试成年现状_3', '公务员', '2020-09-23 16:17:28', '测试入党时间文字_3', '群众', '2021-11-28 16:02:30', '测试第二党派_3', '测试第三党派_3', '2025-11-06 11:01:22', '测试人员管理状态_3', '测试管理类别_3', '6101677722824962', '测试统计关系所在单位_3', '测试简历数据3');
INSERT INTO `civil_servant_person` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `adult_status`, `cadre_mgmt_category`, `work_start_time`, `party_join_time_text`, `political_status`, `party_join_time`, `second_party`, `third_party`, `registration_time`, `person_mgmt_status`, `mgmt_category`, `id_card_no`, `stats_unit`, `resume`) VALUES ('王洋', '男', '1995-03-25', '陕西省咸阳市', '陕西省渭南市', '测试成年现状_4', '参照公务员法管理人员', '2025-11-24 15:53:35', '测试入党时间文字_4', '共青团员', '2024-02-02 14:48:11', '测试第二党派_4', '测试第三党派_4', '2025-06-07 14:39:15', '测试人员管理状态_4', '测试管理类别_4', '6101565781241975', '测试统计关系所在单位_4', '测试简历数据4');
INSERT INTO `civil_servant_person` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `adult_status`, `cadre_mgmt_category`, `work_start_time`, `party_join_time_text`, `political_status`, `party_join_time`, `second_party`, `third_party`, `registration_time`, `person_mgmt_status`, `mgmt_category`, `id_card_no`, `stats_unit`, `resume`) VALUES ('刘杰', '女', '1970-07-11', '陕西省延安市', '陕西省延安市', '测试成年现状_5', '参照公务员法管理人员', '2022-06-04 13:34:04', '测试入党时间文字_5', '群众', '2023-04-17 12:49:46', '测试第二党派_5', '测试第三党派_5', '2023-07-26 15:32:22', '测试人员管理状态_5', '测试管理类别_5', '6101625247188588', '测试统计关系所在单位_5', '测试简历数据5');

-- ----------------------------
-- Test data for: 公务员职务信息 (civil_servant_position)
-- ----------------------------
INSERT INTO `civil_servant_position` (`position_subject_id`, `work_unit_position_short`, `work_unit_position`, `position_level`, `appointment_time`, `appointment_status`, `removal_time`, `removal_doc`, `position_change_reason`, `position_change_time`, `position_change_doc`, `is_leader`, `is_concurrent`) VALUES ('测试职务信息主题_1', '测试现工作单位及职务简称_1', '测试现工作单位及职务_1', '副处级', '2025-02-26 16:34:34', '进行中', '2022-08-20 09:20:57', '测试免职文件_1', '测试职务变动原因_1', '2023-03-19 10:25:06', '测试职务变动文件_1', 0, 0);
INSERT INTO `civil_servant_position` (`position_subject_id`, `work_unit_position_short`, `work_unit_position`, `position_level`, `appointment_time`, `appointment_status`, `removal_time`, `removal_doc`, `position_change_reason`, `position_change_time`, `position_change_doc`, `is_leader`, `is_concurrent`) VALUES ('测试职务信息主题_2', '测试现工作单位及职务简称_2', '测试现工作单位及职务_2', '副科级', '2025-01-02 17:19:24', '待审核', '2020-05-08 15:18:17', '测试免职文件_2', '测试职务变动原因_2', '2025-01-05 10:07:47', '测试职务变动文件_2', 1, 1);
INSERT INTO `civil_servant_position` (`position_subject_id`, `work_unit_position_short`, `work_unit_position`, `position_level`, `appointment_time`, `appointment_status`, `removal_time`, `removal_doc`, `position_change_reason`, `position_change_time`, `position_change_doc`, `is_leader`, `is_concurrent`) VALUES ('测试职务信息主题_3', '测试现工作单位及职务简称_3', '测试现工作单位及职务_3', '正科级', '2022-04-24 15:56:14', '已完成', '2023-11-23 10:07:04', '测试免职文件_3', '测试职务变动原因_3', '2020-01-13 09:19:52', '测试职务变动文件_3', 1, 0);
INSERT INTO `civil_servant_position` (`position_subject_id`, `work_unit_position_short`, `work_unit_position`, `position_level`, `appointment_time`, `appointment_status`, `removal_time`, `removal_doc`, `position_change_reason`, `position_change_time`, `position_change_doc`, `is_leader`, `is_concurrent`) VALUES ('测试职务信息主题_4', '测试现工作单位及职务简称_4', '测试现工作单位及职务_4', '正科级', '2024-02-24 08:37:28', '已取消', '2022-12-16 13:47:15', '测试免职文件_4', '测试职务变动原因_4', '2022-10-15 15:21:08', '测试职务变动文件_4', 1, 0);
INSERT INTO `civil_servant_position` (`position_subject_id`, `work_unit_position_short`, `work_unit_position`, `position_level`, `appointment_time`, `appointment_status`, `removal_time`, `removal_doc`, `position_change_reason`, `position_change_time`, `position_change_doc`, `is_leader`, `is_concurrent`) VALUES ('测试职务信息主题_5', '测试现工作单位及职务简称_5', '测试现工作单位及职务_5', '副科级', '2021-06-01 17:13:15', '已完成', '2022-01-03 13:19:49', '测试免职文件_5', '测试职务变动原因_5', '2024-02-27 16:33:23', '测试职务变动文件_5', 0, 0);

-- ----------------------------
-- Test data for: 公务员考核信息 (civil_servant_assessment)
-- ----------------------------
INSERT INTO `civil_servant_assessment` (`assessment_subject_id`, `assessment_result`, `assessment_year`) VALUES ('测试考核信息主题_1', '基本称职', '2025');
INSERT INTO `civil_servant_assessment` (`assessment_subject_id`, `assessment_result`, `assessment_year`) VALUES ('测试考核信息主题_2', '基本称职', '2020');
INSERT INTO `civil_servant_assessment` (`assessment_subject_id`, `assessment_result`, `assessment_year`) VALUES ('测试考核信息主题_3', '称职', '2023');
INSERT INTO `civil_servant_assessment` (`assessment_subject_id`, `assessment_result`, `assessment_year`) VALUES ('测试考核信息主题_4', '称职', '2020');
INSERT INTO `civil_servant_assessment` (`assessment_subject_id`, `assessment_result`, `assessment_year`) VALUES ('测试考核信息主题_5', '不称职', '2020');

-- ----------------------------
-- Test data for: 公务员奖惩信息 (civil_servant_reward)
-- ----------------------------
INSERT INTO `civil_servant_reward` (`reward_subject_id`, `reward_name`, `reward_category`, `reward_time`, `reward_approve_authority`, `approve_doc_no`, `approve_date`, `approve_authority_level`, `has_merit`, `merit_level`, `revoke_date`) VALUES ('测试奖励信息主题_1', '优秀共产党员1', '授予荣誉称号', '2022-10-15 16:59:28', '陕西省委组织部', '测试批准文号_1', '1988-04-04', '测试批准机关级别_1', 0, '测试记功层次_1', '1986-08-11');
INSERT INTO `civil_servant_reward` (`reward_subject_id`, `reward_name`, `reward_category`, `reward_time`, `reward_approve_authority`, `approve_doc_no`, `approve_date`, `approve_authority_level`, `has_merit`, `merit_level`, `revoke_date`) VALUES ('测试奖励信息主题_2', '优秀共产党员2', '授予荣誉称号', '2023-03-17 08:01:43', '西安市委组织部', '测试批准文号_2', '1963-02-09', '测试批准机关级别_2', 1, '测试记功层次_2', '1991-02-24');
INSERT INTO `civil_servant_reward` (`reward_subject_id`, `reward_name`, `reward_category`, `reward_time`, `reward_approve_authority`, `approve_doc_no`, `approve_date`, `approve_authority_level`, `has_merit`, `merit_level`, `revoke_date`) VALUES ('测试奖励信息主题_3', '优秀共产党员3', '记功', '2025-02-23 14:19:33', '陕西省人力资源和社会保障厅', '测试批准文号_3', '1992-07-04', '测试批准机关级别_3', 0, '测试记功层次_3', '1960-07-25');
INSERT INTO `civil_servant_reward` (`reward_subject_id`, `reward_name`, `reward_category`, `reward_time`, `reward_approve_authority`, `approve_doc_no`, `approve_date`, `approve_authority_level`, `has_merit`, `merit_level`, `revoke_date`) VALUES ('测试奖励信息主题_4', '优秀共产党员4', '记功', '2021-09-08 16:16:45', '陕西省委组织部', '测试批准文号_4', '1977-07-24', '测试批准机关级别_4', 1, '测试记功层次_4', '1992-10-03');
INSERT INTO `civil_servant_reward` (`reward_subject_id`, `reward_name`, `reward_category`, `reward_time`, `reward_approve_authority`, `approve_doc_no`, `approve_date`, `approve_authority_level`, `has_merit`, `merit_level`, `revoke_date`) VALUES ('测试奖励信息主题_5', '优秀共产党员5', '记功', '2025-05-06 12:57:30', '陕西省委组织部', '测试批准文号_5', '1986-02-04', '测试批准机关级别_5', 0, '测试记功层次_5', '1974-04-26');

-- ----------------------------
-- Test data for: 公务员考核信息 (civil_servant_assessment_2)
-- ----------------------------
INSERT INTO `civil_servant_assessment_2` (`assessment_subject_id`, `assessment_result`, `assessment_year`) VALUES ('测试考核信息主题_1', '优秀', '2020');
INSERT INTO `civil_servant_assessment_2` (`assessment_subject_id`, `assessment_result`, `assessment_year`) VALUES ('测试考核信息主题_2', '不称职', '2024');
INSERT INTO `civil_servant_assessment_2` (`assessment_subject_id`, `assessment_result`, `assessment_year`) VALUES ('测试考核信息主题_3', '基本称职', '2023');
INSERT INTO `civil_servant_assessment_2` (`assessment_subject_id`, `assessment_result`, `assessment_year`) VALUES ('测试考核信息主题_4', '称职', '2020');
INSERT INTO `civil_servant_assessment_2` (`assessment_subject_id`, `assessment_result`, `assessment_year`) VALUES ('测试考核信息主题_5', '称职', '2022');

-- ----------------------------
-- Test data for: 公务员专业技术职务信息 (civil_servant_tech_title)
-- ----------------------------
INSERT INTO `civil_servant_tech_title` (`tech_subject_id`, `tech_qual_name`, `qual_obtain_time`, `qual_obtain_way`, `current_tech_qual`, `review_exam_name`) VALUES ('测试专业技术信息主题_1', '测试专业技术资格名称_1', '2024-05-15 13:53:22', '测试取得资格途径_1', '测试当前专业技术任职资格名称_1', '测试评审会或考试名称_1');
INSERT INTO `civil_servant_tech_title` (`tech_subject_id`, `tech_qual_name`, `qual_obtain_time`, `qual_obtain_way`, `current_tech_qual`, `review_exam_name`) VALUES ('测试专业技术信息主题_2', '测试专业技术资格名称_2', '2020-03-15 08:32:30', '测试取得资格途径_2', '测试当前专业技术任职资格名称_2', '测试评审会或考试名称_2');
INSERT INTO `civil_servant_tech_title` (`tech_subject_id`, `tech_qual_name`, `qual_obtain_time`, `qual_obtain_way`, `current_tech_qual`, `review_exam_name`) VALUES ('测试专业技术信息主题_3', '测试专业技术资格名称_3', '2024-07-28 09:20:20', '测试取得资格途径_3', '测试当前专业技术任职资格名称_3', '测试评审会或考试名称_3');
INSERT INTO `civil_servant_tech_title` (`tech_subject_id`, `tech_qual_name`, `qual_obtain_time`, `qual_obtain_way`, `current_tech_qual`, `review_exam_name`) VALUES ('测试专业技术信息主题_4', '测试专业技术资格名称_4', '2022-07-07 18:08:38', '测试取得资格途径_4', '测试当前专业技术任职资格名称_4', '测试评审会或考试名称_4');
INSERT INTO `civil_servant_tech_title` (`tech_subject_id`, `tech_qual_name`, `qual_obtain_time`, `qual_obtain_way`, `current_tech_qual`, `review_exam_name`) VALUES ('测试专业技术信息主题_5', '测试专业技术资格名称_5', '2023-09-26 16:40:58', '测试取得资格途径_5', '测试当前专业技术任职资格名称_5', '测试评审会或考试名称_5');

-- ----------------------------
-- Test data for: 公务员学历学位信息 (civil_servant_education)
-- ----------------------------
INSERT INTO `civil_servant_education` (`edu_degree_subject_id`, `education_name`, `degree_code`, `degree_name`, `enroll_time`, `graduate_time`, `degree_grant_time`, `school_name`, `major_name`, `education_category`, `study_years`, `highest_fulltime_edu_flag`, `highest_fulltime_edu`, `highest_degree_flag`, `highest_degree_edu_flag`, `highest_degree_edu`) VALUES ('测试学历学位信息主题_1', '博士研究生', '测试学位代码_1', '硕士', '2021-06-24 11:50:50', '2022-02-21 09:59:19', '2022-12-22 13:08:08', '宝鸡市委组织部', '测试所学专业名称_1', '测试教育类别_1', '测试学制年限_1', '测试最高全日制学历标', '测试最高全日制学历_1', '测试最高学位标识_1', '测试最高学位学历标识', '测试最高学位学历_1');
INSERT INTO `civil_servant_education` (`edu_degree_subject_id`, `education_name`, `degree_code`, `degree_name`, `enroll_time`, `graduate_time`, `degree_grant_time`, `school_name`, `major_name`, `education_category`, `study_years`, `highest_fulltime_edu_flag`, `highest_fulltime_edu`, `highest_degree_flag`, `highest_degree_edu_flag`, `highest_degree_edu`) VALUES ('测试学历学位信息主题_2', '大学专科', '测试学位代码_2', '博士', '2020-07-03 10:39:12', '2020-08-26 15:50:13', '2024-09-25 12:32:33', '西安市委组织部', '测试所学专业名称_2', '测试教育类别_2', '测试学制年限_2', '测试最高全日制学历标', '测试最高全日制学历_2', '测试最高学位标识_2', '测试最高学位学历标识', '测试最高学位学历_2');
INSERT INTO `civil_servant_education` (`edu_degree_subject_id`, `education_name`, `degree_code`, `degree_name`, `enroll_time`, `graduate_time`, `degree_grant_time`, `school_name`, `major_name`, `education_category`, `study_years`, `highest_fulltime_edu_flag`, `highest_fulltime_edu`, `highest_degree_flag`, `highest_degree_edu_flag`, `highest_degree_edu`) VALUES ('测试学历学位信息主题_3', '大学专科', '测试学位代码_3', '硕士', '2023-10-08 17:22:19', '2025-07-19 11:58:29', '2024-12-02 17:33:25', '陕西省人力资源和社会保障厅', '测试所学专业名称_3', '测试教育类别_3', '测试学制年限_3', '测试最高全日制学历标', '测试最高全日制学历_3', '测试最高学位标识_3', '测试最高学位学历标识', '测试最高学位学历_3');
INSERT INTO `civil_servant_education` (`edu_degree_subject_id`, `education_name`, `degree_code`, `degree_name`, `enroll_time`, `graduate_time`, `degree_grant_time`, `school_name`, `major_name`, `education_category`, `study_years`, `highest_fulltime_edu_flag`, `highest_fulltime_edu`, `highest_degree_flag`, `highest_degree_edu_flag`, `highest_degree_edu`) VALUES ('测试学历学位信息主题_4', '博士研究生', '测试学位代码_4', '硕士', '2021-02-09 10:19:14', '2020-01-21 08:06:40', '2023-05-19 14:04:35', '陕西省人力资源和社会保障厅', '测试所学专业名称_4', '测试教育类别_4', '测试学制年限_4', '测试最高全日制学历标', '测试最高全日制学历_4', '测试最高学位标识_4', '测试最高学位学历标识', '测试最高学位学历_4');
INSERT INTO `civil_servant_education` (`edu_degree_subject_id`, `education_name`, `degree_code`, `degree_name`, `enroll_time`, `graduate_time`, `degree_grant_time`, `school_name`, `major_name`, `education_category`, `study_years`, `highest_fulltime_edu_flag`, `highest_fulltime_edu`, `highest_degree_flag`, `highest_degree_edu_flag`, `highest_degree_edu`) VALUES ('测试学历学位信息主题_5', '博士研究生', '测试学位代码_5', '博士', '2025-09-05 09:40:47', '2025-04-28 13:03:39', '2024-05-22 09:24:19', '陕西省委组织部', '测试所学专业名称_5', '测试教育类别_5', '测试学制年限_5', '测试最高全日制学历标', '测试最高全日制学历_5', '测试最高学位标识_5', '测试最高学位学历标识', '测试最高学位学历_5');

-- ----------------------------
-- Test data for: 公务员家庭成员信息 (civil_servant_family)
-- ----------------------------
INSERT INTO `civil_servant_family` (`family_subject_id`, `name`, `gender`, `birth_date`, `work_unit_position`, `relationship`) VALUES ('测试家庭成员信息主题_1', '杨杰', '女', '1998-05-12', '测试工作单位及职务_1', '测试与本人关系_1');
INSERT INTO `civil_servant_family` (`family_subject_id`, `name`, `gender`, `birth_date`, `work_unit_position`, `relationship`) VALUES ('测试家庭成员信息主题_2', '赵强', '女', '1965-07-01', '测试工作单位及职务_2', '测试与本人关系_2');
INSERT INTO `civil_servant_family` (`family_subject_id`, `name`, `gender`, `birth_date`, `work_unit_position`, `relationship`) VALUES ('测试家庭成员信息主题_3', '陈静', '男', '1973-05-24', '测试工作单位及职务_3', '测试与本人关系_3');
INSERT INTO `civil_servant_family` (`family_subject_id`, `name`, `gender`, `birth_date`, `work_unit_position`, `relationship`) VALUES ('测试家庭成员信息主题_4', '杨伟', '女', '1998-10-17', '测试工作单位及职务_4', '测试与本人关系_4');
INSERT INTO `civil_servant_family` (`family_subject_id`, `name`, `gender`, `birth_date`, `work_unit_position`, `relationship`) VALUES ('测试家庭成员信息主题_5', '刘明', '男', '1960-09-23', '测试工作单位及职务_5', '测试与本人关系_5');

-- ----------------------------
-- Test data for: 公务员工资信息 (civil_servant_salary)
-- ----------------------------
INSERT INTO `civil_servant_salary` (`salary_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('测试工资信息主题_1', '周平', '男', '1983-10-19', '陕西省宝鸡市', '陕西省延安市', '6101786899165854', '测试照片_1', '离职', '公务员', '嘉奖', '优秀共产党员1', '测试授予荣誉称号级别_1', '1997-11-08', '测试奖励原因数据1', '测试奖励说明数据1', '副科级', '测试批准机关性质_1');
INSERT INTO `civil_servant_salary` (`salary_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('测试工资信息主题_2', '黄明', '男', '1988-08-06', '陕西省渭南市', '陕西省延安市', '6101461287411504', '测试照片_2', '在职', '事业单位人员', '嘉奖', '优秀共产党员2', '测试授予荣誉称号级别_2', '1968-07-03', '测试奖励原因数据2', '测试奖励说明数据2', '副科级', '测试批准机关性质_2');
INSERT INTO `civil_servant_salary` (`salary_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('测试工资信息主题_3', '吴娟', '女', '1971-01-23', '陕西省延安市', '陕西省延安市', '6101332057842619', '测试照片_3', '离职', '参照公务员法管理人员', '授予荣誉称号', '优秀共产党员3', '测试授予荣誉称号级别_3', '1964-08-02', '测试奖励原因数据3', '测试奖励说明数据3', '副处级', '测试批准机关性质_3');
INSERT INTO `civil_servant_salary` (`salary_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('测试工资信息主题_4', '陈平', '男', '1968-09-24', '陕西省咸阳市', '陕西省西安市', '6101203887698855', '测试照片_4', '退休', '参照公务员法管理人员', '授予荣誉称号', '优秀共产党员4', '测试授予荣誉称号级别_4', '1990-11-10', '测试奖励原因数据4', '测试奖励说明数据4', '正科级', '测试批准机关性质_4');
INSERT INTO `civil_servant_salary` (`salary_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('测试工资信息主题_5', '杨伟', '男', '1963-06-24', '陕西省咸阳市', '陕西省渭南市', '6101536203497742', '测试照片_5', '离职', '公务员', '记功', '优秀共产党员5', '测试授予荣誉称号级别_5', '1961-01-20', '测试奖励原因数据5', '测试奖励说明数据5', '正厅级', '测试批准机关性质_5');

-- ----------------------------
-- Test data for: 公务员出国（境）信息 (civil_servant_abroad)
-- ----------------------------
INSERT INTO `civil_servant_abroad` (`abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('测试出国（境）信息主题_1', '杨娜', '男', '1995-06-14', '陕西省宝鸡市', '陕西省咸阳市', '6101234427287433', '测试照片_1', '离职', '公务员', '嘉奖', '优秀共产党员1', '测试授予荣誉称号级别_1', '1986-11-25', '测试奖励原因数据1', '测试奖励说明数据1', '正科级', '测试批准机关性质_1');
INSERT INTO `civil_servant_abroad` (`abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('测试出国（境）信息主题_2', '李刚', '女', '1966-05-17', '陕西省延安市', '陕西省西安市', '6101734384945130', '测试照片_2', '离职', '公务员', '嘉奖', '优秀共产党员2', '测试授予荣誉称号级别_2', '1980-01-18', '测试奖励原因数据2', '测试奖励说明数据2', '副科级', '测试批准机关性质_2');
INSERT INTO `civil_servant_abroad` (`abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('测试出国（境）信息主题_3', '杨丽', '女', '1980-08-11', '陕西省宝鸡市', '陕西省延安市', '6101775661418879', '测试照片_3', '离职', '参照公务员法管理人员', '记功', '优秀共产党员3', '测试授予荣誉称号级别_3', '1997-08-18', '测试奖励原因数据3', '测试奖励说明数据3', '正处级', '测试批准机关性质_3');
INSERT INTO `civil_servant_abroad` (`abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('测试出国（境）信息主题_4', '赵平', '男', '1966-10-04', '陕西省渭南市', '陕西省延安市', '6101948411716640', '测试照片_4', '退休', '公务员', '记功', '优秀共产党员4', '测试授予荣誉称号级别_4', '1981-09-11', '测试奖励原因数据4', '测试奖励说明数据4', '副厅级', '测试批准机关性质_4');
INSERT INTO `civil_servant_abroad` (`abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('测试出国（境）信息主题_5', '吴霞', '男', '1990-12-12', '陕西省渭南市', '陕西省延安市', '6101298410356067', '测试照片_5', '退休', '事业单位人员', '嘉奖', '优秀共产党员5', '测试授予荣誉称号级别_5', '1980-08-03', '测试奖励原因数据5', '测试奖励说明数据5', '正科级', '测试批准机关性质_5');

-- ----------------------------
-- Test data for: 公务员档案信息 (civil_servant_archive)
-- ----------------------------
INSERT INTO `civil_servant_archive` (`archive_subject_id`, `archive_no`, `archive_category`, `archive_material`, `storage_location`, `archive_form_time`, `receive_date`, `confidential_no`, `material_category`, `page_count`, `id`) VALUES ('测试档案信息主题_1', 'DABH000001', '测试档案类别_1', '测试档案材料_1', '测试存放地点_1', '2021-04-19 18:07:03', '1978-02-22', 'JYH000001', '测试材料类别_1', 50, 'id_0001');
INSERT INTO `civil_servant_archive` (`archive_subject_id`, `archive_no`, `archive_category`, `archive_material`, `storage_location`, `archive_form_time`, `receive_date`, `confidential_no`, `material_category`, `page_count`, `id`) VALUES ('测试档案信息主题_2', 'DABH000002', '测试档案类别_2', '测试档案材料_2', '测试存放地点_2', '2024-09-05 08:24:13', '2000-06-23', 'JYH000002', '测试材料类别_2', 67, 'id_0002');
INSERT INTO `civil_servant_archive` (`archive_subject_id`, `archive_no`, `archive_category`, `archive_material`, `storage_location`, `archive_form_time`, `receive_date`, `confidential_no`, `material_category`, `page_count`, `id`) VALUES ('测试档案信息主题_3', 'DABH000003', '测试档案类别_3', '测试档案材料_3', '测试存放地点_3', '2024-09-26 16:19:10', '1992-04-22', 'JYH000003', '测试材料类别_3', 96, 'id_0003');
INSERT INTO `civil_servant_archive` (`archive_subject_id`, `archive_no`, `archive_category`, `archive_material`, `storage_location`, `archive_form_time`, `receive_date`, `confidential_no`, `material_category`, `page_count`, `id`) VALUES ('测试档案信息主题_4', 'DABH000004', '测试档案类别_4', '测试档案材料_4', '测试存放地点_4', '2024-08-05 15:37:50', '1998-06-19', 'JYH000004', '测试材料类别_4', 84, 'id_0004');
INSERT INTO `civil_servant_archive` (`archive_subject_id`, `archive_no`, `archive_category`, `archive_material`, `storage_location`, `archive_form_time`, `receive_date`, `confidential_no`, `material_category`, `page_count`, `id`) VALUES ('测试档案信息主题_5', 'DABH000005', '测试档案类别_5', '测试档案材料_5', '测试存放地点_5', '2024-10-23 16:02:44', '1977-07-16', 'JYH000005', '测试材料类别_5', 42, 'id_0005');
