-- ============================================
-- 数据库: sx_cadre_info
-- 自动生成测试数据
-- ============================================
USE `sx_cadre_info`;

-- ----------------------------
-- Test data for: 干部学习培训信息 (cadre_training)
-- ----------------------------
INSERT INTO `cadre_training` (`training_unit`, `training_time`, `training_location`, `training_content`, `allow_internet`, `host_unit`, `undertaking_unit`, `task_doc_id`, `has_graduation`) VALUES ('陕西省人力资源和社会保障厅', '2023-04-28 09:17:55', '测试培训地点_1', '测试培训内容数据1', 0, '陕西省人力资源和社会保障厅', '陕西省人力资源和社会保障厅', '测试任务书编号关联ID_1', 0);
INSERT INTO `cadre_training` (`training_unit`, `training_time`, `training_location`, `training_content`, `allow_internet`, `host_unit`, `undertaking_unit`, `task_doc_id`, `has_graduation`) VALUES ('陕西省委组织部', '2022-02-27 12:18:49', '测试培训地点_2', '测试培训内容数据2', 0, '宝鸡市委组织部', '延安市委组织部', '测试任务书编号关联ID_2', 1);
INSERT INTO `cadre_training` (`training_unit`, `training_time`, `training_location`, `training_content`, `allow_internet`, `host_unit`, `undertaking_unit`, `task_doc_id`, `has_graduation`) VALUES ('陕西省人力资源和社会保障厅', '2020-06-25 09:57:36', '测试培训地点_3', '测试培训内容数据3', 0, '陕西省人力资源和社会保障厅', '宝鸡市委组织部', '测试任务书编号关联ID_3', 0);
INSERT INTO `cadre_training` (`training_unit`, `training_time`, `training_location`, `training_content`, `allow_internet`, `host_unit`, `undertaking_unit`, `task_doc_id`, `has_graduation`) VALUES ('延安市委组织部', '2022-09-11 12:01:26', '测试培训地点_4', '测试培训内容数据4', 1, '宝鸡市委组织部', '延安市委组织部', '测试任务书编号关联ID_4', 1);
INSERT INTO `cadre_training` (`training_unit`, `training_time`, `training_location`, `training_content`, `allow_internet`, `host_unit`, `undertaking_unit`, `task_doc_id`, `has_graduation`) VALUES ('西安市委组织部', '2024-06-09 17:48:50', '测试培训地点_5', '测试培训内容数据5', 0, '西安市委组织部', '西安市委组织部', '测试任务书编号关联ID_5', 0);

-- ----------------------------
-- Test data for: 干部挂职锻炼信息 (cadre_secondment)
-- ----------------------------
INSERT INTO `cadre_secondment` (`secondment_unit`, `secondment_position`, `duration`, `form`, `post`, `location`, `secondment_types`, `secondment_start_time`, `secondment_end_time`, `unit_audit`, `remark`) VALUES ('宝鸡市委组织部', '测试挂职职务_1', '测试期限_1', '测试形式_1', '测试岗位_1', '测试地点_1', '测试挂职类型集合_1', '2020-06-14 13:39:05', '2023-07-04 10:19:34', '测试单位审核_1', '测试备注_1');
INSERT INTO `cadre_secondment` (`secondment_unit`, `secondment_position`, `duration`, `form`, `post`, `location`, `secondment_types`, `secondment_start_time`, `secondment_end_time`, `unit_audit`, `remark`) VALUES ('延安市委组织部', '测试挂职职务_2', '测试期限_2', '测试形式_2', '测试岗位_2', '测试地点_2', '测试挂职类型集合_2', '2025-06-08 12:38:38', '2025-10-22 17:36:47', '测试单位审核_2', '测试备注_2');
INSERT INTO `cadre_secondment` (`secondment_unit`, `secondment_position`, `duration`, `form`, `post`, `location`, `secondment_types`, `secondment_start_time`, `secondment_end_time`, `unit_audit`, `remark`) VALUES ('陕西省委组织部', '测试挂职职务_3', '测试期限_3', '测试形式_3', '测试岗位_3', '测试地点_3', '测试挂职类型集合_3', '2022-08-25 17:30:58', '2024-10-10 14:08:49', '测试单位审核_3', '测试备注_3');
INSERT INTO `cadre_secondment` (`secondment_unit`, `secondment_position`, `duration`, `form`, `post`, `location`, `secondment_types`, `secondment_start_time`, `secondment_end_time`, `unit_audit`, `remark`) VALUES ('西安市委组织部', '测试挂职职务_4', '测试期限_4', '测试形式_4', '测试岗位_4', '测试地点_4', '测试挂职类型集合_4', '2022-02-04 14:34:08', '2020-03-04 10:04:48', '测试单位审核_4', '测试备注_4');
INSERT INTO `cadre_secondment` (`secondment_unit`, `secondment_position`, `duration`, `form`, `post`, `location`, `secondment_types`, `secondment_start_time`, `secondment_end_time`, `unit_audit`, `remark`) VALUES ('延安市委组织部', '测试挂职职务_5', '测试期限_5', '测试形式_5', '测试岗位_5', '测试地点_5', '测试挂职类型集合_5', '2020-09-24 18:21:49', '2023-08-22 10:49:27', '测试单位审核_5', '测试备注_5');

-- ----------------------------
-- Test data for: 干部因私出国（境）信息 (cadre_private_abroad)
-- ----------------------------
INSERT INTO `cadre_private_abroad` (`private_abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `private_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('测试因私出国（境）信息主题_1', '杨静', '男', '1976-07-18', '陕西省宝鸡市', '陕西省宝鸡市', '6101852232822233', '测试照片_1', '离职', '事业单位人员', '测试因私出国（境）事由_1', '陕西省委组织部', '测试审批文号_1', '1967-05-27', '1977-02-18', '1975-09-06', 'G55768099', '测试护照有效期_1');
INSERT INTO `cadre_private_abroad` (`private_abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `private_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('测试因私出国（境）信息主题_2', '赵磊', '男', '1980-01-07', '陕西省咸阳市', '陕西省西安市', '6101274462833358', '测试照片_2', '离职', '公务员', '测试因私出国（境）事由_2', '陕西省人力资源和社会保障厅', '测试审批文号_2', '1973-12-13', '1998-12-15', '1983-01-11', 'G27738941', '测试护照有效期_2');
INSERT INTO `cadre_private_abroad` (`private_abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `private_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('测试因私出国（境）信息主题_3', '赵军', '男', '2000-12-09', '陕西省渭南市', '陕西省咸阳市', '6101305273936304', '测试照片_3', '离职', '公务员', '测试因私出国（境）事由_3', '西安市委组织部', '测试审批文号_3', '1974-04-15', '1973-09-12', '1987-03-26', 'G54340333', '测试护照有效期_3');
INSERT INTO `cadre_private_abroad` (`private_abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `private_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('测试因私出国（境）信息主题_4', '陈霞', '女', '1976-03-05', '陕西省咸阳市', '陕西省延安市', '6101567384474742', '测试照片_4', '退休', '事业单位人员', '测试因私出国（境）事由_4', '陕西省人力资源和社会保障厅', '测试审批文号_4', '1985-06-20', '1983-06-28', '1961-05-01', 'G66275876', '测试护照有效期_4');
INSERT INTO `cadre_private_abroad` (`private_abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `private_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('测试因私出国（境）信息主题_5', '赵丽', '女', '1973-04-11', '陕西省宝鸡市', '陕西省西安市', '6101563976203630', '测试照片_5', '离职', '事业单位人员', '测试因私出国（境）事由_5', '西安市委组织部', '测试审批文号_5', '1960-04-02', '1988-06-11', '1980-07-25', 'G31897759', '测试护照有效期_5');

-- ----------------------------
-- Test data for: 干部因公出国（境）信息 (cadre_official_abroad)
-- ----------------------------
INSERT INTO `cadre_official_abroad` (`official_abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `official_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('测试因公出国（境）信息主题_1', '吴平', '女', '1991-11-14', '陕西省西安市', '陕西省延安市', '6101152638446518', '测试照片_1', '在职', '参照公务员法管理人员', '测试因公出国（境）事由_1', '陕西省人力资源和社会保障厅', '测试审批文号_1', '1985-09-08', '1990-04-23', '1972-08-17', 'G70713662', '测试护照有效期_1');
INSERT INTO `cadre_official_abroad` (`official_abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `official_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('测试因公出国（境）信息主题_2', '陈娟', '男', '1966-11-27', '陕西省宝鸡市', '陕西省渭南市', '6101193357280970', '测试照片_2', '离职', '公务员', '测试因公出国（境）事由_2', '陕西省委组织部', '测试审批文号_2', '1989-11-02', '2000-06-24', '1968-08-26', 'G45488659', '测试护照有效期_2');
INSERT INTO `cadre_official_abroad` (`official_abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `official_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('测试因公出国（境）信息主题_3', '吴杰', '男', '1985-05-11', '陕西省咸阳市', '陕西省渭南市', '6101279110169161', '测试照片_3', '离职', '公务员', '测试因公出国（境）事由_3', '陕西省人力资源和社会保障厅', '测试审批文号_3', '1987-09-24', '1985-10-24', '1990-11-09', 'G26609563', '测试护照有效期_3');
INSERT INTO `cadre_official_abroad` (`official_abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `official_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('测试因公出国（境）信息主题_4', '周军', '男', '1985-03-08', '陕西省咸阳市', '陕西省渭南市', '6101513085144125', '测试照片_4', '退休', '公务员', '测试因公出国（境）事由_4', '西安市委组织部', '测试审批文号_4', '1990-12-13', '1975-04-08', '1966-06-07', 'G64027491', '测试护照有效期_4');
INSERT INTO `cadre_official_abroad` (`official_abroad_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `official_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('测试因公出国（境）信息主题_5', '赵涛', '男', '1971-09-25', '陕西省渭南市', '陕西省延安市', '6101246325752182', '测试照片_5', '退休', '参照公务员法管理人员', '测试因公出国（境）事由_5', '西安市委组织部', '测试审批文号_5', '1993-05-17', '1967-04-09', '1969-06-24', 'G22708753', '测试护照有效期_5');
