-- ============================================
-- 数据库: sx_org_cadre_mgmt
-- 自动生成测试数据
-- ============================================
USE `sx_org_cadre_mgmt`;

-- ----------------------------
-- Test data for: 干部任免信息 (cadre_appointment)
-- ----------------------------
INSERT INTO `cadre_appointment` (`appointment_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `current_position_level`, `current_position`, `appointment_time`, `removal_time`, `removal_doc`, `is_promoted`, `is_transfer`, `is_demoted`, `appointment_doc_no`, `appointment_authority`, `appointment_type`, `appointment_reason`, `appointment_basis`, `appointment_result`, `appointment_remark`) VALUES ('测试任免信息主题_1', '吴娟', '女', '1981-10-14', '陕西省宝鸡市', '陕西省咸阳市', '6101243647624843', '测试照片_1', '退休', '参照公务员法管理人员', '科长', '副处级', '科长', '2024-12-09 13:46:25', '2025-05-24 18:17:40', '测试免职文件_1', 1, 0, 1, '测试任免文号_1', '测试任免机关_1', '测试任免类型_1', '测试任免事由_1', '测试任免依据_1', '测试任免结果_1', '测试任免备注_1');
INSERT INTO `cadre_appointment` (`appointment_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `current_position_level`, `current_position`, `appointment_time`, `removal_time`, `removal_doc`, `is_promoted`, `is_transfer`, `is_demoted`, `appointment_doc_no`, `appointment_authority`, `appointment_type`, `appointment_reason`, `appointment_basis`, `appointment_result`, `appointment_remark`) VALUES ('测试任免信息主题_2', '黄娜', '男', '1962-09-12', '陕西省咸阳市', '陕西省延安市', '6101265666399813', '测试照片_2', '在职', '公务员', '副处长', '正处级', '副主任科员', '2025-10-23 08:25:03', '2025-04-14 10:41:11', '测试免职文件_2', 0, 0, 1, '测试任免文号_2', '测试任免机关_2', '测试任免类型_2', '测试任免事由_2', '测试任免依据_2', '测试任免结果_2', '测试任免备注_2');
INSERT INTO `cadre_appointment` (`appointment_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `current_position_level`, `current_position`, `appointment_time`, `removal_time`, `removal_doc`, `is_promoted`, `is_transfer`, `is_demoted`, `appointment_doc_no`, `appointment_authority`, `appointment_type`, `appointment_reason`, `appointment_basis`, `appointment_result`, `appointment_remark`) VALUES ('测试任免信息主题_3', '周丽', '男', '1989-04-03', '陕西省咸阳市', '陕西省渭南市', '6101751521173748', '测试照片_3', '离职', '公务员', '副科长', '正处级', '副主任科员', '2022-12-24 09:18:00', '2023-12-17 11:44:00', '测试免职文件_3', 0, 1, 0, '测试任免文号_3', '测试任免机关_3', '测试任免类型_3', '测试任免事由_3', '测试任免依据_3', '测试任免结果_3', '测试任免备注_3');
INSERT INTO `cadre_appointment` (`appointment_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `current_position_level`, `current_position`, `appointment_time`, `removal_time`, `removal_doc`, `is_promoted`, `is_transfer`, `is_demoted`, `appointment_doc_no`, `appointment_authority`, `appointment_type`, `appointment_reason`, `appointment_basis`, `appointment_result`, `appointment_remark`) VALUES ('测试任免信息主题_4', '王勇', '女', '1995-03-10', '陕西省咸阳市', '陕西省渭南市', '6101559289081453', '测试照片_4', '在职', '公务员', '处长', '正处级', '处长', '2023-09-07 11:42:17', '2024-04-17 12:14:42', '测试免职文件_4', 0, 0, 0, '测试任免文号_4', '测试任免机关_4', '测试任免类型_4', '测试任免事由_4', '测试任免依据_4', '测试任免结果_4', '测试任免备注_4');
INSERT INTO `cadre_appointment` (`appointment_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `current_position_level`, `current_position`, `appointment_time`, `removal_time`, `removal_doc`, `is_promoted`, `is_transfer`, `is_demoted`, `appointment_doc_no`, `appointment_authority`, `appointment_type`, `appointment_reason`, `appointment_basis`, `appointment_result`, `appointment_remark`) VALUES ('测试任免信息主题_5', '刘刚', '男', '1998-04-06', '陕西省延安市', '陕西省延安市', '6101978636986331', '测试照片_5', '退休', '公务员', '副科长', '正科级', '副处长', '2023-05-06 17:54:53', '2021-04-22 17:44:15', '测试免职文件_5', 0, 1, 0, '测试任免文号_5', '测试任免机关_5', '测试任免类型_5', '测试任免事由_5', '测试任免依据_5', '测试任免结果_5', '测试任免备注_5');

-- ----------------------------
-- Test data for: 干部任职信息 (cadre_position)
-- ----------------------------
INSERT INTO `cadre_position` (`position_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `current_position_level`, `current_position`, `appointment_time`, `removal_time`, `removal_doc`, `is_promoted`, `is_transfer`, `is_demoted`, `appointment_doc_no`, `appointment_authority`, `appointment_type`, `appointment_reason`, `appointment_basis`, `appointment_result`, `appointment_remark`) VALUES ('测试任职信息主题_1', '王伟', '女', '1977-05-19', '陕西省西安市', '陕西省延安市', '6101445240255616', '测试照片_1', '退休', '公务员', '处长', '正科级', '副处长', '2023-11-20 14:22:05', '2021-09-10 08:48:37', '测试免职文件_1', 0, 0, 1, '测试任免文号_1', '测试任免机关_1', '测试任免类型_1', '测试任免事由_1', '测试任免依据_1', '测试任免结果_1', '测试任免备注_1');
INSERT INTO `cadre_position` (`position_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `current_position_level`, `current_position`, `appointment_time`, `removal_time`, `removal_doc`, `is_promoted`, `is_transfer`, `is_demoted`, `appointment_doc_no`, `appointment_authority`, `appointment_type`, `appointment_reason`, `appointment_basis`, `appointment_result`, `appointment_remark`) VALUES ('测试任职信息主题_2', '周军', '男', '1997-01-24', '陕西省宝鸡市', '陕西省西安市', '6101514632439597', '测试照片_2', '离职', '公务员', '副处长', '正厅级', '副主任科员', '2022-05-10 14:53:32', '2024-10-02 16:50:41', '测试免职文件_2', 0, 1, 0, '测试任免文号_2', '测试任免机关_2', '测试任免类型_2', '测试任免事由_2', '测试任免依据_2', '测试任免结果_2', '测试任免备注_2');
INSERT INTO `cadre_position` (`position_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `current_position_level`, `current_position`, `appointment_time`, `removal_time`, `removal_doc`, `is_promoted`, `is_transfer`, `is_demoted`, `appointment_doc_no`, `appointment_authority`, `appointment_type`, `appointment_reason`, `appointment_basis`, `appointment_result`, `appointment_remark`) VALUES ('测试任职信息主题_3', '王平', '女', '1964-01-27', '陕西省延安市', '陕西省咸阳市', '6101821366972828', '测试照片_3', '退休', '参照公务员法管理人员', '处长', '副处级', '科长', '2025-02-07 11:36:42', '2021-09-26 14:30:45', '测试免职文件_3', 1, 1, 0, '测试任免文号_3', '测试任免机关_3', '测试任免类型_3', '测试任免事由_3', '测试任免依据_3', '测试任免结果_3', '测试任免备注_3');
INSERT INTO `cadre_position` (`position_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `current_position_level`, `current_position`, `appointment_time`, `removal_time`, `removal_doc`, `is_promoted`, `is_transfer`, `is_demoted`, `appointment_doc_no`, `appointment_authority`, `appointment_type`, `appointment_reason`, `appointment_basis`, `appointment_result`, `appointment_remark`) VALUES ('测试任职信息主题_4', '赵强', '男', '1985-12-28', '陕西省渭南市', '陕西省宝鸡市', '6101493530338448', '测试照片_4', '退休', '公务员', '主任科员', '正处级', '副处长', '2023-06-23 09:05:59', '2025-10-01 17:12:48', '测试免职文件_4', 0, 1, 1, '测试任免文号_4', '测试任免机关_4', '测试任免类型_4', '测试任免事由_4', '测试任免依据_4', '测试任免结果_4', '测试任免备注_4');
INSERT INTO `cadre_position` (`position_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `current_position_level`, `current_position`, `appointment_time`, `removal_time`, `removal_doc`, `is_promoted`, `is_transfer`, `is_demoted`, `appointment_doc_no`, `appointment_authority`, `appointment_type`, `appointment_reason`, `appointment_basis`, `appointment_result`, `appointment_remark`) VALUES ('测试任职信息主题_5', '王霞', '女', '1983-05-06', '陕西省西安市', '陕西省宝鸡市', '6101819455337558', '测试照片_5', '在职', '事业单位人员', '处长', '正处级', '处长', '2020-12-02 16:55:17', '2021-02-13 08:52:31', '测试免职文件_5', 0, 0, 1, '测试任免文号_5', '测试任免机关_5', '测试任免类型_5', '测试任免事由_5', '测试任免依据_5', '测试任免结果_5', '测试任免备注_5');

-- ----------------------------
-- Test data for: 干部人事调配信息 (cadre_deployment_info)
-- ----------------------------
INSERT INTO `cadre_deployment_info` (`deployment_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `profession`, `tech_qual_name`, `title_level`, `qual_obtain_date`, `qual_obtain_way`, `current_tech_qual`) VALUES ('测试调配信息主题_1', '黄明', '男', '1976-01-22', '陕西省宝鸡市', '陕西省咸阳市', '6101142920389363', '测试照片_1', '在职', '公务员', '测试从事专业_1', '测试专业技术资格名称_1', '测试职称级别_1', '1983-06-04', '测试取得资格途径_1', '测试当前专业技术任职资格名称_1');
INSERT INTO `cadre_deployment_info` (`deployment_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `profession`, `tech_qual_name`, `title_level`, `qual_obtain_date`, `qual_obtain_way`, `current_tech_qual`) VALUES ('测试调配信息主题_2', '刘明', '男', '1977-12-19', '陕西省宝鸡市', '陕西省宝鸡市', '6101109896195678', '测试照片_2', '在职', '公务员', '测试从事专业_2', '测试专业技术资格名称_2', '测试职称级别_2', '1990-04-27', '测试取得资格途径_2', '测试当前专业技术任职资格名称_2');
INSERT INTO `cadre_deployment_info` (`deployment_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `profession`, `tech_qual_name`, `title_level`, `qual_obtain_date`, `qual_obtain_way`, `current_tech_qual`) VALUES ('测试调配信息主题_3', '陈芳', '女', '1962-07-09', '陕西省延安市', '陕西省咸阳市', '6101147389853192', '测试照片_3', '退休', '参照公务员法管理人员', '测试从事专业_3', '测试专业技术资格名称_3', '测试职称级别_3', '1962-03-17', '测试取得资格途径_3', '测试当前专业技术任职资格名称_3');
INSERT INTO `cadre_deployment_info` (`deployment_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `profession`, `tech_qual_name`, `title_level`, `qual_obtain_date`, `qual_obtain_way`, `current_tech_qual`) VALUES ('测试调配信息主题_4', '王平', '女', '1979-08-04', '陕西省西安市', '陕西省咸阳市', '6101643002562790', '测试照片_4', '离职', '事业单位人员', '测试从事专业_4', '测试专业技术资格名称_4', '测试职称级别_4', '1988-09-11', '测试取得资格途径_4', '测试当前专业技术任职资格名称_4');
INSERT INTO `cadre_deployment_info` (`deployment_subject_id`, `name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `profession`, `tech_qual_name`, `title_level`, `qual_obtain_date`, `qual_obtain_way`, `current_tech_qual`) VALUES ('测试调配信息主题_5', '黄平', '女', '1997-01-22', '陕西省延安市', '陕西省咸阳市', '6101734059352861', '测试照片_5', '离职', '参照公务员法管理人员', '测试从事专业_5', '测试专业技术资格名称_5', '测试职称级别_5', '1969-05-26', '测试取得资格途径_5', '测试当前专业技术任职资格名称_5');

-- ----------------------------
-- Test data for: 干部学历学位信息 (cadre_education)
-- ----------------------------
INSERT INTO `cadre_education` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `education`, `education_cert_no`, `education_supplement`, `enroll_date`, `graduate_period`, `study_years`, `school_name`, `school_relation`, `degree_category`, `major_name`, `study_completion`, `education_level`, `major_category`, `degree`, `degree_level`, `degree_grant_date`, `degree_grant_unit`, `education_category`) VALUES ('黄勇', '男', '1981-10-11', '陕西省西安市', '陕西省咸阳市', '6101666107719593', '测试照片_1', '在职', '公务员', '博士研究生', '测试学历证书号码_1', '测试学历补充_1', '1963-01-28', '测试毕（肄）业期_1', '测试学制_1', '陕西省委组织部', '测试院校关系_1', '测试获学位类别_1', '测试所学专业名称_1', '测试学习完成情况_1', '大学本科', '测试所学专业类别_1', '博士', '测试学位级别_1', '1961-06-21', '测试学位授予单位_1', '测试学历类别_1');
INSERT INTO `cadre_education` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `education`, `education_cert_no`, `education_supplement`, `enroll_date`, `graduate_period`, `study_years`, `school_name`, `school_relation`, `degree_category`, `major_name`, `study_completion`, `education_level`, `major_category`, `degree`, `degree_level`, `degree_grant_date`, `degree_grant_unit`, `education_category`) VALUES ('周杰', '女', '1984-06-22', '陕西省咸阳市', '陕西省咸阳市', '6101609648516376', '测试照片_2', '退休', '公务员', '硕士研究生', '测试学历证书号码_2', '测试学历补充_2', '1966-02-05', '测试毕（肄）业期_2', '测试学制_2', '西安市委组织部', '测试院校关系_2', '测试获学位类别_2', '测试所学专业名称_2', '测试学习完成情况_2', '博士研究生', '测试所学专业类别_2', '硕士', '测试学位级别_2', '1984-07-10', '测试学位授予单位_2', '测试学历类别_2');
INSERT INTO `cadre_education` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `education`, `education_cert_no`, `education_supplement`, `enroll_date`, `graduate_period`, `study_years`, `school_name`, `school_relation`, `degree_category`, `major_name`, `study_completion`, `education_level`, `major_category`, `degree`, `degree_level`, `degree_grant_date`, `degree_grant_unit`, `education_category`) VALUES ('黄强', '男', '1992-06-22', '陕西省西安市', '陕西省咸阳市', '6101670714248932', '测试照片_3', '在职', '事业单位人员', '硕士研究生', '测试学历证书号码_3', '测试学历补充_3', '1972-06-17', '测试毕（肄）业期_3', '测试学制_3', '宝鸡市委组织部', '测试院校关系_3', '测试获学位类别_3', '测试所学专业名称_3', '测试学习完成情况_3', '大学专科', '测试所学专业类别_3', '博士', '测试学位级别_3', '1973-09-18', '测试学位授予单位_3', '测试学历类别_3');
INSERT INTO `cadre_education` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `education`, `education_cert_no`, `education_supplement`, `enroll_date`, `graduate_period`, `study_years`, `school_name`, `school_relation`, `degree_category`, `major_name`, `study_completion`, `education_level`, `major_category`, `degree`, `degree_level`, `degree_grant_date`, `degree_grant_unit`, `education_category`) VALUES ('杨娟', '男', '1962-01-25', '陕西省渭南市', '陕西省西安市', '6101134431923093', '测试照片_4', '在职', '事业单位人员', '大学本科', '测试学历证书号码_4', '测试学历补充_4', '1995-10-11', '测试毕（肄）业期_4', '测试学制_4', '陕西省人力资源和社会保障厅', '测试院校关系_4', '测试获学位类别_4', '测试所学专业名称_4', '测试学习完成情况_4', '硕士研究生', '测试所学专业类别_4', '学士', '测试学位级别_4', '1981-08-20', '测试学位授予单位_4', '测试学历类别_4');
INSERT INTO `cadre_education` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `education`, `education_cert_no`, `education_supplement`, `enroll_date`, `graduate_period`, `study_years`, `school_name`, `school_relation`, `degree_category`, `major_name`, `study_completion`, `education_level`, `major_category`, `degree`, `degree_level`, `degree_grant_date`, `degree_grant_unit`, `education_category`) VALUES ('吴艳', '女', '1962-12-21', '陕西省宝鸡市', '陕西省西安市', '6101497827275885', '测试照片_5', '退休', '参照公务员法管理人员', '大学本科', '测试学历证书号码_5', '测试学历补充_5', '1989-07-09', '测试毕（肄）业期_5', '测试学制_5', '西安市委组织部', '测试院校关系_5', '测试获学位类别_5', '测试所学专业名称_5', '测试学习完成情况_5', '硕士研究生', '测试所学专业类别_5', '硕士', '测试学位级别_5', '1996-07-14', '测试学位授予单位_5', '测试学历类别_5');

-- ----------------------------
-- Test data for: 干部的奖惩信息 (cadre_reward_punish)
-- ----------------------------
INSERT INTO `cadre_reward_punish` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('杨军', '女', '1975-07-13', '陕西省西安市', '陕西省延安市', '6101155885774700', '测试照片_1', '在职', '公务员', '授予荣誉称号', '优秀共产党员1', '测试授予荣誉称号级别_1', '1993-08-26', '测试奖励原因数据1', '测试奖励说明数据1', '正科级', '测试批准机关性质_1');
INSERT INTO `cadre_reward_punish` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('李伟', '女', '1978-04-14', '陕西省宝鸡市', '陕西省宝鸡市', '6101805981112450', '测试照片_2', '在职', '事业单位人员', '嘉奖', '优秀共产党员2', '测试授予荣誉称号级别_2', '1991-05-04', '测试奖励原因数据2', '测试奖励说明数据2', '正处级', '测试批准机关性质_2');
INSERT INTO `cadre_reward_punish` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('吴勇', '女', '1992-07-16', '陕西省宝鸡市', '陕西省咸阳市', '6101414503309759', '测试照片_3', '退休', '参照公务员法管理人员', '授予荣誉称号', '优秀共产党员3', '测试授予荣誉称号级别_3', '1970-04-10', '测试奖励原因数据3', '测试奖励说明数据3', '副科级', '测试批准机关性质_3');
INSERT INTO `cadre_reward_punish` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('李强', '男', '1998-03-07', '陕西省咸阳市', '陕西省西安市', '6101366566031799', '测试照片_4', '离职', '参照公务员法管理人员', '授予荣誉称号', '优秀共产党员4', '测试授予荣誉称号级别_4', '1988-01-12', '测试奖励原因数据4', '测试奖励说明数据4', '副处级', '测试批准机关性质_4');
INSERT INTO `cadre_reward_punish` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('吴明', '女', '1963-04-15', '陕西省西安市', '陕西省延安市', '6101388120416257', '测试照片_5', '在职', '事业单位人员', '嘉奖', '优秀共产党员5', '测试授予荣誉称号级别_5', '2000-01-26', '测试奖励原因数据5', '测试奖励说明数据5', '正处级', '测试批准机关性质_5');

-- ----------------------------
-- Test data for: 干部的职务信息 (cadre_duty)
-- ----------------------------
INSERT INTO `cadre_duty` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `position_category`, `position_level`) VALUES ('李娟', '女', '1977-11-20', '陕西省西安市', '陕西省渭南市', '6101284389565173', '测试照片_1', '在职', '事业单位人员', '副处长', '公务员', '正科级');
INSERT INTO `cadre_duty` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `position_category`, `position_level`) VALUES ('李敏', '女', '1991-05-10', '陕西省咸阳市', '陕西省西安市', '6101376818628291', '测试照片_2', '在职', '事业单位人员', '副处长', '参照公务员法管理人员', '副科级');
INSERT INTO `cadre_duty` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `position_category`, `position_level`) VALUES ('黄平', '男', '1998-05-16', '陕西省延安市', '陕西省渭南市', '6101560873426245', '测试照片_3', '在职', '事业单位人员', '处长', '事业单位人员', '副科级');
INSERT INTO `cadre_duty` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `position_category`, `position_level`) VALUES ('吴艳', '女', '1960-06-17', '陕西省延安市', '陕西省咸阳市', '6101610315941834', '测试照片_4', '离职', '事业单位人员', '副处长', '事业单位人员', '正厅级');
INSERT INTO `cadre_duty` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `position_category`, `position_level`) VALUES ('陈芳', '男', '1961-07-11', '陕西省西安市', '陕西省渭南市', '6101638773319880', '测试照片_5', '退休', '事业单位人员', '副处长', '事业单位人员', '正处级');

-- ----------------------------
-- Test data for: 干部的任职信息 (cadre_position_info)
-- ----------------------------
INSERT INTO `cadre_position_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `profession`, `tech_qual_name`, `title_level`, `qual_obtain_date`, `qual_obtain_way`, `current_tech_qual`) VALUES ('陈霞', '男', '1977-03-23', '陕西省西安市', '陕西省延安市', '6101661838412993', '测试照片_1', '在职', '事业单位人员', '测试从事专业_1', '测试专业技术资格名称_1', '测试职称级别_1', '1991-11-10', '测试取得资格途径_1', '测试当前专业技术任职资格名称_1');
INSERT INTO `cadre_position_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `profession`, `tech_qual_name`, `title_level`, `qual_obtain_date`, `qual_obtain_way`, `current_tech_qual`) VALUES ('黄刚', '男', '1962-12-03', '陕西省咸阳市', '陕西省宝鸡市', '6101246542325129', '测试照片_2', '在职', '参照公务员法管理人员', '测试从事专业_2', '测试专业技术资格名称_2', '测试职称级别_2', '1979-01-17', '测试取得资格途径_2', '测试当前专业技术任职资格名称_2');
INSERT INTO `cadre_position_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `profession`, `tech_qual_name`, `title_level`, `qual_obtain_date`, `qual_obtain_way`, `current_tech_qual`) VALUES ('吴洋', '女', '1983-09-19', '陕西省咸阳市', '陕西省延安市', '6101815587859568', '测试照片_3', '退休', '参照公务员法管理人员', '测试从事专业_3', '测试专业技术资格名称_3', '测试职称级别_3', '1974-01-07', '测试取得资格途径_3', '测试当前专业技术任职资格名称_3');
INSERT INTO `cadre_position_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `profession`, `tech_qual_name`, `title_level`, `qual_obtain_date`, `qual_obtain_way`, `current_tech_qual`) VALUES ('黄勇', '女', '1978-11-26', '陕西省咸阳市', '陕西省渭南市', '6101243039114579', '测试照片_4', '离职', '公务员', '测试从事专业_4', '测试专业技术资格名称_4', '测试职称级别_4', '1999-02-14', '测试取得资格途径_4', '测试当前专业技术任职资格名称_4');
INSERT INTO `cadre_position_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `profession`, `tech_qual_name`, `title_level`, `qual_obtain_date`, `qual_obtain_way`, `current_tech_qual`) VALUES ('赵杰', '男', '1988-06-14', '陕西省西安市', '陕西省延安市', '6101159418303911', '测试照片_5', '退休', '参照公务员法管理人员', '测试从事专业_5', '测试专业技术资格名称_5', '测试职称级别_5', '1992-10-06', '测试取得资格途径_5', '测试当前专业技术任职资格名称_5');

-- ----------------------------
-- Test data for: 干部的学历学位信息 (cadre_edu_degree)
-- ----------------------------
INSERT INTO `cadre_edu_degree` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `education`, `education_cert_no`, `education_supplement`, `enroll_date`, `graduate_period`, `study_years`, `school_name`, `school_relation`, `degree_category`, `major_name`, `study_completion`, `education_level`, `major_category`, `degree`, `degree_level`, `degree_grant_date`, `degree_grant_unit`, `education_category`) VALUES ('赵霞', '女', '1977-07-08', '陕西省延安市', '陕西省延安市', '6101178108929614', '测试照片_1', '离职', '事业单位人员', '大学专科', '测试学历证书号码_1', '测试学历补充_1', '1983-10-23', '测试毕（肄）业期_1', '测试学制_1', '宝鸡市委组织部', '测试院校关系_1', '测试获学位类别_1', '测试所学专业名称_1', '测试学习完成情况_1', '大学本科', '测试所学专业类别_1', '硕士', '测试学位级别_1', '1984-12-22', '测试学位授予单位_1', '测试学历类别_1');
INSERT INTO `cadre_edu_degree` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `education`, `education_cert_no`, `education_supplement`, `enroll_date`, `graduate_period`, `study_years`, `school_name`, `school_relation`, `degree_category`, `major_name`, `study_completion`, `education_level`, `major_category`, `degree`, `degree_level`, `degree_grant_date`, `degree_grant_unit`, `education_category`) VALUES ('吴超', '男', '1975-07-25', '陕西省宝鸡市', '陕西省渭南市', '6101692618841889', '测试照片_2', '在职', '参照公务员法管理人员', '大学专科', '测试学历证书号码_2', '测试学历补充_2', '1975-12-14', '测试毕（肄）业期_2', '测试学制_2', '延安市委组织部', '测试院校关系_2', '测试获学位类别_2', '测试所学专业名称_2', '测试学习完成情况_2', '大学专科', '测试所学专业类别_2', '学士', '测试学位级别_2', '1966-11-22', '测试学位授予单位_2', '测试学历类别_2');
INSERT INTO `cadre_edu_degree` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `education`, `education_cert_no`, `education_supplement`, `enroll_date`, `graduate_period`, `study_years`, `school_name`, `school_relation`, `degree_category`, `major_name`, `study_completion`, `education_level`, `major_category`, `degree`, `degree_level`, `degree_grant_date`, `degree_grant_unit`, `education_category`) VALUES ('赵静', '男', '1964-03-09', '陕西省宝鸡市', '陕西省渭南市', '6101252325273289', '测试照片_3', '退休', '参照公务员法管理人员', '硕士研究生', '测试学历证书号码_3', '测试学历补充_3', '1964-02-27', '测试毕（肄）业期_3', '测试学制_3', '陕西省委组织部', '测试院校关系_3', '测试获学位类别_3', '测试所学专业名称_3', '测试学习完成情况_3', '大学专科', '测试所学专业类别_3', '硕士', '测试学位级别_3', '1971-11-06', '测试学位授予单位_3', '测试学历类别_3');
INSERT INTO `cadre_edu_degree` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `education`, `education_cert_no`, `education_supplement`, `enroll_date`, `graduate_period`, `study_years`, `school_name`, `school_relation`, `degree_category`, `major_name`, `study_completion`, `education_level`, `major_category`, `degree`, `degree_level`, `degree_grant_date`, `degree_grant_unit`, `education_category`) VALUES ('陈明', '男', '1985-01-10', '陕西省宝鸡市', '陕西省宝鸡市', '6101397003808010', '测试照片_4', '退休', '公务员', '博士研究生', '测试学历证书号码_4', '测试学历补充_4', '1993-11-15', '测试毕（肄）业期_4', '测试学制_4', '延安市委组织部', '测试院校关系_4', '测试获学位类别_4', '测试所学专业名称_4', '测试学习完成情况_4', '大学专科', '测试所学专业类别_4', '学士', '测试学位级别_4', '1967-12-19', '测试学位授予单位_4', '测试学历类别_4');
INSERT INTO `cadre_edu_degree` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `education`, `education_cert_no`, `education_supplement`, `enroll_date`, `graduate_period`, `study_years`, `school_name`, `school_relation`, `degree_category`, `major_name`, `study_completion`, `education_level`, `major_category`, `degree`, `degree_level`, `degree_grant_date`, `degree_grant_unit`, `education_category`) VALUES ('张勇', '女', '1968-06-21', '陕西省西安市', '陕西省渭南市', '6101384503995247', '测试照片_5', '在职', '公务员', '硕士研究生', '测试学历证书号码_5', '测试学历补充_5', '1967-03-04', '测试毕（肄）业期_5', '测试学制_5', '陕西省委组织部', '测试院校关系_5', '测试获学位类别_5', '测试所学专业名称_5', '测试学习完成情况_5', '博士研究生', '测试所学专业类别_5', '学士', '测试学位级别_5', '1962-05-05', '测试学位授予单位_5', '测试学历类别_5');

-- ----------------------------
-- Test data for: 干部的奖惩信息 (cadre_reward_punish_2)
-- ----------------------------
INSERT INTO `cadre_reward_punish_2` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('赵霞', '男', '1997-03-21', '陕西省咸阳市', '陕西省渭南市', '6101735960581006', '测试照片_1', '在职', '事业单位人员', '记功', '优秀共产党员1', '测试授予荣誉称号级别_1', '1971-10-08', '测试奖励原因数据1', '测试奖励说明数据1', '副厅级', '测试批准机关性质_1');
INSERT INTO `cadre_reward_punish_2` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('陈超', '女', '1982-07-19', '陕西省宝鸡市', '陕西省宝鸡市', '6101308131946907', '测试照片_2', '退休', '公务员', '记功', '优秀共产党员2', '测试授予荣誉称号级别_2', '1979-06-25', '测试奖励原因数据2', '测试奖励说明数据2', '正科级', '测试批准机关性质_2');
INSERT INTO `cadre_reward_punish_2` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('吴平', '男', '1964-09-14', '陕西省咸阳市', '陕西省西安市', '6101911757450290', '测试照片_3', '离职', '事业单位人员', '授予荣誉称号', '优秀共产党员3', '测试授予荣誉称号级别_3', '1979-04-13', '测试奖励原因数据3', '测试奖励说明数据3', '正科级', '测试批准机关性质_3');
INSERT INTO `cadre_reward_punish_2` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('黄丽', '女', '1998-10-27', '陕西省宝鸡市', '陕西省西安市', '6101883168712855', '测试照片_4', '离职', '参照公务员法管理人员', '授予荣誉称号', '优秀共产党员4', '测试授予荣誉称号级别_4', '1984-07-03', '测试奖励原因数据4', '测试奖励说明数据4', '副处级', '测试批准机关性质_4');
INSERT INTO `cadre_reward_punish_2` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `reward_category`, `reward_name`, `honor_level`, `reward_approve_date`, `reward_reason`, `reward_desc`, `reward_position_level`, `approve_authority_nature`) VALUES ('黄强', '男', '1964-12-11', '陕西省渭南市', '陕西省渭南市', '6101937451471750', '测试照片_5', '退休', '参照公务员法管理人员', '嘉奖', '优秀共产党员5', '测试授予荣誉称号级别_5', '1972-04-03', '测试奖励原因数据5', '测试奖励说明数据5', '副科级', '测试批准机关性质_5');

-- ----------------------------
-- Test data for: 干部的任职信息 (cadre_position_info_2)
-- ----------------------------
INSERT INTO `cadre_position_info_2` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `position_category`, `position_level`) VALUES ('赵敏', '女', '1963-02-05', '陕西省延安市', '陕西省咸阳市', '6101882590917265', '测试照片_1', '离职', '事业单位人员', '副处长', '公务员', '副厅级');
INSERT INTO `cadre_position_info_2` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `position_category`, `position_level`) VALUES ('王强', '男', '1993-06-11', '陕西省宝鸡市', '陕西省延安市', '6101940651524991', '测试照片_2', '离职', '事业单位人员', '副处长', '公务员', '副厅级');
INSERT INTO `cadre_position_info_2` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `position_category`, `position_level`) VALUES ('周强', '男', '2000-06-05', '陕西省延安市', '陕西省渭南市', '6101710580994492', '测试照片_3', '离职', '公务员', '副主任科员', '事业单位人员', '正厅级');
INSERT INTO `cadre_position_info_2` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `position_category`, `position_level`) VALUES ('李霞', '女', '1997-05-26', '陕西省宝鸡市', '陕西省延安市', '6101357488927233', '测试照片_4', '离职', '参照公务员法管理人员', '副科长', '参照公务员法管理人员', '副厅级');
INSERT INTO `cadre_position_info_2` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `position_name`, `position_category`, `position_level`) VALUES ('黄涛', '男', '1967-07-17', '陕西省咸阳市', '陕西省西安市', '6101113008124789', '测试照片_5', '离职', '参照公务员法管理人员', '处长', '事业单位人员', '副处级');

-- ----------------------------
-- Test data for: 干部的因公出国（境）信息 (cadre_official_abroad_info)
-- ----------------------------
INSERT INTO `cadre_official_abroad_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `official_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('周明', '男', '1966-04-26', '陕西省渭南市', '陕西省延安市', '6101696148485443', '测试照片_1', '退休', '参照公务员法管理人员', '测试因公出国（境）事由_1', '陕西省委组织部', '测试审批文号_1', '1975-01-09', '1977-02-14', '1966-12-21', 'G56388270', '测试护照有效期_1');
INSERT INTO `cadre_official_abroad_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `official_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('杨超', '女', '1982-03-24', '陕西省渭南市', '陕西省渭南市', '6101362631020908', '测试照片_2', '在职', '公务员', '测试因公出国（境）事由_2', '陕西省委组织部', '测试审批文号_2', '1996-03-02', '1964-02-16', '1970-11-24', 'G63819780', '测试护照有效期_2');
INSERT INTO `cadre_official_abroad_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `official_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('王静', '女', '1967-11-18', '陕西省宝鸡市', '陕西省宝鸡市', '6101758472021004', '测试照片_3', '在职', '事业单位人员', '测试因公出国（境）事由_3', '陕西省委组织部', '测试审批文号_3', '1988-06-10', '1973-10-12', '2000-02-06', 'G14823197', '测试护照有效期_3');
INSERT INTO `cadre_official_abroad_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `official_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('赵洋', '女', '1996-10-01', '陕西省延安市', '陕西省延安市', '6101173033179628', '测试照片_4', '在职', '事业单位人员', '测试因公出国（境）事由_4', '西安市委组织部', '测试审批文号_4', '1962-05-15', '1992-10-27', '1982-12-17', 'G72240016', '测试护照有效期_4');
INSERT INTO `cadre_official_abroad_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `official_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('周丽', '女', '1964-05-11', '陕西省延安市', '陕西省咸阳市', '6101252515330670', '测试照片_5', '在职', '参照公务员法管理人员', '测试因公出国（境）事由_5', '陕西省委组织部', '测试审批文号_5', '1981-06-03', '1967-01-28', '1977-11-05', 'G80192033', '测试护照有效期_5');

-- ----------------------------
-- Test data for: 干部的因私出国（境）信息 (cadre_private_abroad_info)
-- ----------------------------
INSERT INTO `cadre_private_abroad_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `private_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('周明', '女', '1997-08-15', '陕西省西安市', '陕西省渭南市', '6101192098783520', '测试照片_1', '在职', '参照公务员法管理人员', '测试因私出国（境）事由_1', '西安市委组织部', '测试审批文号_1', '1963-10-07', '1980-06-18', '1968-09-21', 'G46351398', '测试护照有效期_1');
INSERT INTO `cadre_private_abroad_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `private_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('黄洋', '女', '1963-04-10', '陕西省延安市', '陕西省西安市', '6101210203426272', '测试照片_2', '离职', '公务员', '测试因私出国（境）事由_2', '陕西省委组织部', '测试审批文号_2', '2000-10-17', '1968-10-15', '1983-01-26', 'G91639456', '测试护照有效期_2');
INSERT INTO `cadre_private_abroad_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `private_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('吴强', '女', '1965-01-04', '陕西省渭南市', '陕西省咸阳市', '6101579959310564', '测试照片_3', '退休', '事业单位人员', '测试因私出国（境）事由_3', '陕西省人力资源和社会保障厅', '测试审批文号_3', '1999-12-17', '1969-02-11', '1984-01-14', 'G14867906', '测试护照有效期_3');
INSERT INTO `cadre_private_abroad_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `private_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('陈霞', '女', '1976-03-08', '陕西省西安市', '陕西省宝鸡市', '6101655189447585', '测试照片_4', '退休', '事业单位人员', '测试因私出国（境）事由_4', '西安市委组织部', '测试审批文号_4', '1992-10-07', '1965-10-26', '1996-12-05', 'G32268892', '测试护照有效期_4');
INSERT INTO `cadre_private_abroad_info` (`name`, `gender`, `birth_date`, `native_place`, `birth_place`, `id_card_no`, `photo`, `person_status`, `cadre_mgmt_category`, `private_abroad_reason`, `approve_authority`, `approve_doc_no`, `approve_date`, `actual_departure_date`, `actual_return_date`, `passport_no`, `passport_validity`) VALUES ('刘娟', '男', '1979-02-02', '陕西省西安市', '陕西省渭南市', '6101698627549865', '测试照片_5', '在职', '事业单位人员', '测试因私出国（境）事由_5', '陕西省委组织部', '测试审批文号_5', '1990-10-18', '1970-01-10', '1961-12-22', 'G99083501', '测试护照有效期_5');
